### PR TITLE
Fix duplicate requests

### LINKED ISSUE #285: Fix bug from merge conflict
- There are two dossierreview.ts files. (One of them should be removed)
- In Dossier.ts, the `discussion` attribute in DossierDetailsDTO that was previously added, was removed from a merge conflict. It should be added back.
- In Dossier.ts, "groupID" should be "groupId"

Bug introduced from merge conflicts of https://github.com/JamesPartsafas/ConcordiaCurriculumManager/pull/280 with https://github.com/JamesPartsafas/ConcordiaCurriculumManager/pull/273

### LINKED ISSUE #286: Fix duplicate requests
This is a subtask of #6 

We should not allow duplicate requests for the same course within a dossier.

[Story Points: 3]
[Priority: High]
[Risk: Medium]

### PR DESCRIPTION
**Pull request by zihao429**
Fix a bug where you could have duplicate course requests. Closes #286

### CODE REVIEW

File: Server/ConcordiaCurriculumManager/Services/CourseService.cs [hunk 1]
```diff
@@ -89,32 +91,39 @@ public async Task<Course> GetCourseDataWithSupportingFilesOrThrowOnDeleted(strin
...
+        if (courseFromDb != null && courseFromDb.CourseState == CourseStateEnum.Accepted)
+        {
+            throw new BadRequestException("The course already exists and is accepted");
+        }
+
+        var isDuplicate = await _dossierRepository.CheckIfCourseRequestExists(initiation.DossierId, initiation.Subject, initiation.Catalog);
+
+        if (isDuplicate)
+        {
+            throw new DuplicateNameException("A course creation request with the course " + initiation.Subject + " " + initiation.Catalog + " already exists.");
```
Comment (JamesPartsafas) [inline Server/ConcordiaCurriculumManager/Services/CourseService.cs:114]: The all 3 methods, (creation, modification, and deletion initiation), you should return a BadRequestException, because our backend is configured to return 400 level errors on those exceptions. Also, you should not specify `A course creation request with the course...` in the exception message, because you don't actually know what type of request it is (it might be a modification or deletion). This again applies to all 3 methods, just have the exception message say `"A course request for " + initiation.Subject + " " + initiation.Catalog + " already exists in this dossier."`

Comment (zihao429) [reply Server/ConcordiaCurriculumManager/Services/CourseService.cs:114]: Sounds good

**Review by JamesPartsafas — APPROVED** [review]
LGTM
