### PR TITLE
86 fix group endpoints

### LINKED ISSUE #86: Fix group-related endpoints
The endpoints in the GroupController return a 405 Not Allowed error when queried, rather than the expected responses.

This is a child task of #21

[Story Points: 2]
[Priority: Medium]
[Risk: Medium]

### PR DESCRIPTION
**Pull request by JamesPartsafas**
Fix error codes in GroupController. Additionally, extract common selectors from Repository classes to their own static class.

Closes #86

### CODE REVIEW

**Review by Dinferno-lol — APPROVED** [review]
All changes seem good, will merge now.

File: Server/ConcordiaCurriculumManager/Repositories/ObjectSelectors.cs [hunk 1]
```diff
@@ -0,0 +1,44 @@
...
+using System.Data;
+using System.Linq.Expressions;
+
+namespace ConcordiaCurriculumManager.Repositories;
+
+public static class ObjectSelectors
+{
+    public static Expression<Func<Role, Role>> RoleSelector() => role => new Role
+    {
+        UserRole = role.UserRole
```
Comment (Ghaith-Chrit) [inline Server/ConcordiaCurriculumManager/Repositories/ObjectSelectors.cs:11]: Looks good. It might be useful to populate all the info into roles in case it is needed to avoid confusion since the values get assigned wrong default values. But that is not a major concern right now. Same for the other selectors.
